// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Acb4zD3HsD5y-NUjglEmk2NS6eTNNNI',
    appId: '1:805014004880:web:ef2ecd6b7c412f857b6415',
    messagingSenderId: '805014004880',
    projectId: 'projeto-software',
    authDomain: 'projeto-software.firebaseapp.com',
    storageBucket: 'projeto-software.appspot.com',
    measurementId: 'G-HVJJ0CDPQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqdpWcpRMdyEX0QwYWWPs6tzzX4wHG1Rs',
    appId: '1:805014004880:android:2b05cb067f7090e87b6415',
    messagingSenderId: '805014004880',
    projectId: 'projeto-software',
    storageBucket: 'projeto-software.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb6WgOnzAsY0DQD2W-guh_4fMK0ZrE6vc',
    appId: '1:805014004880:ios:318b50fbcf69127e7b6415',
    messagingSenderId: '805014004880',
    projectId: 'projeto-software',
    storageBucket: 'projeto-software.appspot.com',
    iosClientId: '805014004880-aad0dl31lc4qcc7fjh4rb4so63lq1q48.apps.googleusercontent.com',
    iosBundleId: 'com.example.finances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb6WgOnzAsY0DQD2W-guh_4fMK0ZrE6vc',
    appId: '1:805014004880:ios:318b50fbcf69127e7b6415',
    messagingSenderId: '805014004880',
    projectId: 'projeto-software',
    storageBucket: 'projeto-software.appspot.com',
    iosClientId: '805014004880-aad0dl31lc4qcc7fjh4rb4so63lq1q48.apps.googleusercontent.com',
    iosBundleId: 'com.example.finances',
  );
}
